# Setup
title: WELCOME! HERE YOU WILL FIND MORE ABOUT ME. PAPERS, PROJECTS, TECH&SKILLS, AND CONTACTS ARE INCLUDED.
# description: WELCOME! HERE YOU WILL FIND MORE ABOUT ME. PAPERS, PROJECTS, TECH&SKILLS, AND CONTACTS ARE INCLUDED.
url: https://cho-sunghyun.github.io
avatar: /assets/img/seonghyun.png
paginate: 5
permalink: pretty
cover_image: /assets/img/bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
logo: logo.png
social:
  name: SeongHyun Cho
  links:
    - https://www.linkedin.com/in/seonghyun-cho
    - https://github.com/cho-sunghyun
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: SeongHyun Cho
  url: https://github.com/cho-sunghyun/
  email: saintcho94@gmail.com
